---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006-grafana
  namespace: grafana
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv0006-grafana
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfsshare/pv0006/grafana
    server: 192.168.1.195
