---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        namespace: grafana
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_INSTALL_PLUGINS
          value: "grafana-clock-panel,grafana-simple-json-datasource"
        - name: GF_PATHS_DATA
          value: "/var/lib/grafana"
        image: grafana/grafana:7.3.6-ubuntu
        ports:
          - name: https-port
            containerPort: 3000
        volumeMounts:
          - name: grafana-pv-storage
            mountPath: /var/lib/grafana
          - name: grafana-config
            mountPath: /etc/grafana/
          - name: grafana-cert
            mountPath: /etc/ssl/grafana/crt/
          - name: grafana-key
            mountPath: /etc/ssl/grafana/key/
      volumes:
        - name: grafana-pv-storage
          persistentVolumeClaim:
            claimName: pv0006-grafana
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-cert
          secret:
            secretName: grafana-tls
            items:
              - key: tls.crt
                path: certificate.csr
        - name: grafana-key
          secret:
            secretName: grafana-tls
            items:
              - key: tls.key
                path: private_key.key

