---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0006-grafana
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pv0006-grafana
  resources:
    requests:
      storage: 20Gi
